import { SpacingValues, TypographySettings } from "../types";

export const initialTypography: TypographySettings = {
  desktop: {
    fontFamily: "raleway",
    h1Size: 61,
    h2Size: 49,
    h3Size: 25,
    p1Size: 16,
    p2Size: 13,
    headingLineHeight: 1.15,
    bodyLineHeight: 1.6,
    headingLetterSpacing: -0.022,
    bodyLetterSpacing: 0,
    headingFontWeight: 700,
    bodyFontWeight: 400,
  },
  tablet: {
    fontFamily: "raleway",
    h1Size: 48,
    h2Size: 38,
    h3Size: 22,
    p1Size: 16,
    p2Size: 13,
    headingLineHeight: 1.2,
    bodyLineHeight: 1.6,
    headingLetterSpacing: -0.015,
    bodyLetterSpacing: 0,
    headingFontWeight: 700,
    bodyFontWeight: 400,
  },
  mobile: {
    fontFamily: "raleway",
    h1Size: 36,
    h2Size: 28,
    h3Size: 20,
    p1Size: 16,
    p2Size: 14,
    headingLineHeight: 1.25,
    bodyLineHeight: 1.6,
    headingLetterSpacing: -0.01,
    bodyLetterSpacing: 0,
    headingFontWeight: 700,
    bodyFontWeight: 400,
  },
};

export const initialSpacing: SpacingValues = {
  desktop: {
    pagePaddingTopBottom: 48,
    pagePaddingLeftRight: 64,
    sectionPaddingTopBottom: 32,
    sectionPaddingLeftRight: 32,
    majorSections: 48,
    h1ToContent: 40,
    subsections: 32,
    subtitleToH2: 32,
    h2ToNext: 24,
    aboveButtons: 24,
    h3ToContent: 16,
    bulletPoints: 16,
    paragraphSpacing: 26,
    gridGap2ColHorizontal: 40,
    gridGap2ColVertical: 32,
    gridGap3ColHorizontal: 32,
    gridGap3ColVertical: 24,
    gridGap4ColHorizontal: 24,
    gridGap4ColVertical: 20,
    singleColumnMaxWidth: 720,
  },
  tablet: {
    pagePaddingTopBottom: 40,
    pagePaddingLeftRight: 48,
    sectionPaddingTopBottom: 24,
    sectionPaddingLeftRight: 24,
    majorSections: 40,
    h1ToContent: 32,
    subsections: 24,
    subtitleToH2: 24,
    h2ToNext: 20,
    aboveButtons: 20,
    h3ToContent: 12,
    bulletPoints: 12,
    paragraphSpacing: 22,
    gridGap2ColHorizontal: 32,
    gridGap2ColVertical: 24,
    gridGap3ColHorizontal: 24,
    gridGap3ColVertical: 20,
    gridGap4ColHorizontal: 20,
    gridGap4ColVertical: 16,
    singleColumnMaxWidth: 630,
  },
  mobile: {
    pagePaddingTopBottom: 32,
    pagePaddingLeftRight: 24,
    sectionPaddingTopBottom: 20,
    sectionPaddingLeftRight: 16,
    majorSections: 32,
    h1ToContent: 24,
    subsections: 20,
    subtitleToH2: 20,
    h2ToNext: 16,
    aboveButtons: 16,
    h3ToContent: 12,
    bulletPoints: 12,
    paragraphSpacing: 20,
    gridGap2ColHorizontal: 24,
    gridGap2ColVertical: 20,
    gridGap3ColHorizontal: 20,
    gridGap3ColVertical: 16,
    gridGap4ColHorizontal: 16,
    gridGap4ColVertical: 12,
    singleColumnMaxWidth: 0, // 100% width on mobile
  },
};

export const spacingLabels = {
  // Page & Section Layout
  pagePaddingTopBottom: "Page Padding (Vertical)",
  pagePaddingLeftRight: "Page Padding (Horizontal)",
  sectionPaddingTopBottom: "Section Padding (Vertical)",
  sectionPaddingLeftRight: "Section Padding (Horizontal)",
  majorSections: "Between Major Sections",
  subsections: "Between Subsections",

  // Heading Hierarchy
  h1ToContent: "H1 → Next Element",
  h2ToNext: "H2 → Next Element",
  h3ToContent: "H3 → Next Element",
  subtitleToH2: "Section Label → H2",

  // Content Spacing
  paragraphSpacing: "Paragraph Spacing",
  bulletPoints: "Bullet Point Spacing",

  // Interactive Elements
  aboveButtons: "Above Buttons",

  // Grid Layouts
  gridGap2ColHorizontal: "2-Column Gap (Horizontal)",
  gridGap2ColVertical: "2-Column Gap (Vertical)",
  gridGap3ColHorizontal: "3-Column Gap (Horizontal)",
  gridGap3ColVertical: "3-Column Gap (Vertical)",
  gridGap4ColHorizontal: "4-Column Gap (Horizontal)",
  gridGap4ColVertical: "4-Column Gap (Vertical)",

  // Layout Constraints
  singleColumnMaxWidth: "Single Column Max Width",
};
