import { SpacingValues, TypographySettings } from '../types';

export const initialTypography: TypographySettings = {
  fontFamily: 'raleway',
  h1Size: 61,
  h2Size: 49,
  h3Size: 25,
  p1Size: 16,
  p2Size: 13,
  headingLineHeight: 1.15,
  bodyLineHeight: 1.6,
  headingLetterSpacing: -0.022,
  bodyLetterSpacing: 0,
  headingFontWeight: 700,
  bodyFontWeight: 400,
};

export const initialSpacing: SpacingValues = {
  desktop: {
    pagePaddingTopBottom: 48,
    pagePaddingLeftRight: 64,
    sectionPaddingTopBottom: 32,
    sectionPaddingLeftRight: 32,
    majorSections: 48,
    h1ToContent: 40,
    subsections: 32,
    subtitleToH2: 32,
    h2ToNext: 24,
    aboveButtons: 24,
    h3ToContent: 16,
    bulletPoints: 16,
    paragraphSpacing: 26,
    gridGap2ColHorizontal: 40,
    gridGap2ColVertical: 32,
    gridGap3ColHorizontal: 32,
    gridGap3ColVertical: 24,
    gridGap4ColHorizontal: 24,
    gridGap4ColVertical: 20,
    singleColumnMaxWidth: 720,
  },
  tablet: {
    pagePaddingTopBottom: 40,
    pagePaddingLeftRight: 48,
    sectionPaddingTopBottom: 24,
    sectionPaddingLeftRight: 24,
    majorSections: 40,
    h1ToContent: 32,
    subsections: 24,
    subtitleToH2: 24,
    h2ToNext: 20,
    aboveButtons: 20,
    h3ToContent: 12,
    bulletPoints: 12,
    paragraphSpacing: 22,
    gridGap2ColHorizontal: 32,
    gridGap2ColVertical: 24,
    gridGap3ColHorizontal: 24,
    gridGap3ColVertical: 20,
    gridGap4ColHorizontal: 20,
    gridGap4ColVertical: 16,
    singleColumnMaxWidth: 630,
  },
  mobile: {
    pagePaddingTopBottom: 32,
    pagePaddingLeftRight: 24,
    sectionPaddingTopBottom: 20,
    sectionPaddingLeftRight: 16,
    majorSections: 32,
    h1ToContent: 24,
    subsections: 20,
    subtitleToH2: 20,
    h2ToNext: 16,
    aboveButtons: 16,
    h3ToContent: 12,
    bulletPoints: 12,
    paragraphSpacing: 20,
    gridGap2ColHorizontal: 24,
    gridGap2ColVertical: 20,
    gridGap3ColHorizontal: 20,
    gridGap3ColVertical: 16,
    gridGap4ColHorizontal: 16,
    gridGap4ColVertical: 12,
    singleColumnMaxWidth: 0, // 100% width on mobile
  },
};

export const spacingLabels = {
  pagePaddingTopBottom: 'Page Padding (Top/Bottom)',
  pagePaddingLeftRight: 'Page Padding (Left/Right)',
  sectionPaddingTopBottom: 'Section Padding (Top/Bottom)',
  sectionPaddingLeftRight: 'Section Padding (Left/Right)',
  majorSections: 'Between Major Sections',
  h1ToContent: 'H1 Section Title → Content',
  subsections: 'Between Subsections',
  subtitleToH2: 'Section Label → H2',
  h2ToNext: 'H2 Subsection Header → Next Element',
  aboveButtons: 'Above Buttons',
  h3ToContent: 'H3 Subsection → Content',
  bulletPoints: 'Bullet Point Spacing',
  paragraphSpacing: 'Paragraph Spacing',
  gridGap2ColHorizontal: '2-Column Grid Gap (Horizontal)',
  gridGap2ColVertical: '2-Column Grid Gap (Vertical)',
  gridGap3ColHorizontal: '3-Column Grid Gap (Horizontal)',
  gridGap3ColVertical: '3-Column Grid Gap (Vertical)',
  gridGap4ColHorizontal: '4-Column Grid Gap (Horizontal)',
  gridGap4ColVertical: '4-Column Grid Gap (Vertical)',
  singleColumnMaxWidth: 'Single Column Content Max Width',
};